// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lddtackcnpzdswndqgfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZHRhY2tjbnB6ZHN3bmRxZ2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTY5MDgsImV4cCI6MjA2Njk3MjkwOH0.NPN6E-4RttputzXcVavoOTRGiM9c3T5bLaLPTtJJM4s";

console.log('🔧 Configurando cliente Supabase:');
console.log('  - URL:', SUPABASE_URL);
console.log('  - Key:', SUPABASE_PUBLISHABLE_KEY ? '✅ Configurada' : '❌ Não configurada');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});

// Adicionar listener para debug de mudanças de sessão
supabase.auth.onAuthStateChange((event, session) => {
  console.log('🔄 Supabase Auth State Change:', event);
  console.log('  - Session:', session ? '✅ Existe' : '❌ Não existe');
  console.log('  - User ID:', session?.user?.id || 'null');
  console.log('  - User Email:', session?.user?.email || 'null');
  
  // Verificar localStorage após mudança
  setTimeout(() => {
    const supabaseKeys = Object.keys(localStorage).filter(key => key.includes('supabase'));
    console.log('🔍 Chaves Supabase no localStorage após mudança:', supabaseKeys);
    supabaseKeys.forEach(key => {
      console.log(`  - ${key}:`, localStorage.getItem(key) ? '✅' : '❌');
    });
  }, 100);
});